name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Baixa o código

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Instala o node v16
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --legacy-peer-deps # Instala as dependências

      - name: Build Storybook
        run: npm run build-storybook # Gera a pasta storybook-static

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} # Deployar a pasta storybook-static
